name: Notificaci贸n de Push a Main

on:
  push:
    branches: [ "main" ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificaci贸n a ntfy.sh
        run: |
          curl -d "El Repositorio: $GITHUB_REPOSITORY, Commit: $GITHUB_SHA" \
          -H "Title: Actualizaci贸n de c贸digo" \
          -H "Priority: high" \
          https://ntfy.sh/devops-itla
